docusaurus.config.js
simple & GDPR ok analytics from https://plausible.io
=> Adding Plausible analytics

docs/getting-started/install_capi_operator.md, docs/getting-started/install_turtles_operator.md, docs/tasks/capi-operator/add_infrastructure_provider.md, docs/tasks/capi-operator/basic_cluster_api_provider_installation.md
Improve readability of the quickstart documentation and address outstanding comments from https://github.com/rancher-sandbox/rancher-turtles-docs/pull/12#pullrequestreview-1631018093
=> 📖 Update quickstart to reflect requested changes

docs/getting-started/install_turtles_operator.md
With the [implementation](https://github.com/rancher-sandbox/rancher-turtles/pull/139) of the new functionality to automatically create a secret with the required feature flags in the core provider's namespace, we need to update the documentation to reflect the two differentiated scenarios:
- If user does not provide secret name and namespace: a default secret will be created in the core provider namespace with the minimum required feature flags enabled.
- If user provides both secret name and namespace as helm flags: no secret is created and the user is in charge of creating and managing the secret, which must exist, and is free to add custom environment variables.
Hopefully this is clear in the documentation after the update.
=> docs: update CoreProvider environment variable secret documentation

docs/contributing/development.md, docs/contributing/guidelines.md, sidebars.js
Also fix typos in the contributing guide
=> 📖 Improve development setup notes

docs/intro.md, docs/security/slsa.md, sidebars.js
Inspired by https://fluxcd.io/flux/security/slsa-assessment/
=> Add slsa page to documentation

blog/2023-10-03-early-access-released.md
Small change to update the slack channel to use.
=> docs: update the slack channel

docs/tasks/capi-operator/add_infrastructure_provider.md
Following up on https://github.com/rancher-sandbox/rancher-turtles/pull/282, this PR adds a note on known issues with CAPZ version v1.12.0.
Fixes #55
=> docs: add note on capz versions

docusaurus.config.js, package.json, yarn.lock
Adding local search functionality which supports text highlighting and multiple languages if `zh` translations are added in the future. Additionally, removed the `ts-check` from the config as it was erroring with the new theme addition.
[Search Reference](https://github.com/easyops-cn/docusaurus-search-local)
=> Adding Local Search Functionality

docs/reference-guides/providers.md, sidebars.js
We've had questions on what providers are supported by Turtles. This PR adds a list with the officially supported providers which we can update as we move forward with the project.
=> docs: add list of supported providers

.github/workflows/version-publish.yaml
Fixes #94
In addition to https://github.com/rancher/highlander/issues/89
=> Replace deprecated actions workflow

docs/getting-started/intro.md, versioned_docs/version-0.6/getting-started/intro.md
Applying changes updating the latest and next versions of the introduction landing page with more information in top level header sections about available documentation. Also updated the intro phrasing with CAPI functionality.
=> Update Landing Page Content

docs/reference-guides/providers.md
Add kubeadm to list of supported providers.
=> docs: add kubeadm to list of supported providers

.github/workflows/test-deploy.yaml
- Trigger test workflow on label change
=> Workaround: run test jobs on GH actions bot PR

docs/getting-started/create-first-cluster/using_fleet.md
=> 📖 Update Fleet notes with helm annotations

docs/reference-guides/providers/certified.md
Documentation for https://github.com/rancher/turtles/issues/548
=> Add Elemental experimental provider

docs/getting-started/cluster-class/provision.md
Add missing environment variable to guide on how to create an AKS cluster from a ClusterClass
=> add missing variable to aks cluster class guide

.github/workflows/publish-version.yaml
Add a workflow that automates docs release
=> Automate docs release

docs/next/modules/en/nav.adoc, docs/next/modules/en/pages/reference/features.adoc
Add feature stages page
Fixes: https://github.com/rancher/turtles-docs/issues/135
=> Add feature stages page

docs/next/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
Documentation update for https://github.com/rancher/turtles/pull/1029
=> Remove embedded-capi feature

docs/next/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
Remove deprecated values from Helm chart documentation.
=> docs: update helm chart values

turtles-gh-pages-playbook.yml
Fixes #188
Note that the start page is still 0.15
=> Render 'next' version

docs/next/modules/en/pages/developer-guide/install_capi_operator.adoc, docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc, docs/next/modules/en/pages/index.adoc, docs/next/modules/en/pages/tasks/capi-operator/installing_core_provider.adoc, docs/v0.16/modules/en/pages/developer-guide/install_capi_operator.adoc, docs/v0.16/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc, docs/v0.16/modules/en/pages/index.adoc, docs/v0.16/modules/en/pages/tasks/capi-operator/installing_core_provider.adoc
new release version of docs is available, this patch updates versions of dependencies in the docs
=> 📖 Update dependency versions in the next/v0.16 version of the docs

.github/dependabot.yml
It looks like dependabot jobs are not running. Trying to fix syntax.
=> Fix dependabot yaml syntax

docs/next/modules/en/pages/user/clusters.adoc
Fixes https://github.com/rancher/turtles-docs/issues/81
Fixes https://github.com/rancher/turtles-docs/issues/116
Fixes https://github.com/rancher/turtles-docs/issues/115
=> Add missing provider examples

docs/next/modules/en/pages/operator/airgapped.adoc, docs/next/modules/en/pages/operator/capiprovider.adoc, docs/next/modules/en/pages/operator/chart.adoc, docs/next/modules/en/pages/operator/clusterclass.adoc, docs/v0.17/modules/en/pages/operator/airgapped.adoc, docs/v0.17/modules/en/pages/operator/capiprovider.adoc, docs/v0.17/modules/en/pages/operator/chart.adoc, docs/v0.17/modules/en/pages/operator/clusterclass.adoc
This PR updates the docs to reflect the current set of feature flags that are customisable in Turtles. It also includes some minor syntactic fixes.
=> :book: Minor doc improvements

docs/next/modules/en/pages/developer/development.adoc, docs/next/modules/en/pages/operator/airgapped.adoc, docs/next/modules/en/pages/operator/certification.adoc, docs/next/modules/en/pages/operator/certificationsuite.adoc, docs/next/modules/en/pages/operator/chart.adoc, docs/next/modules/en/pages/operator/clusterclass.adoc, docs/next/modules/en/pages/reference/certified.adoc, docs/next/modules/en/pages/tutorials/first-cluster.adoc, docs/next/modules/en/pages/user/caapf.adoc, docs/next/modules/en/pages/user/clusters.adoc, docs/next/modules/en/pages/user/fleet.adoc, docs/v0.17/modules/en/pages/developer/development.adoc, docs/v0.17/modules/en/pages/operator/airgapped.adoc, docs/v0.17/modules/en/pages/operator/certification.adoc, docs/v0.17/modules/en/pages/operator/certificationsuite.adoc, docs/v0.17/modules/en/pages/operator/chart.adoc, docs/v0.17/modules/en/pages/operator/clusterclass.adoc, docs/v0.17/modules/en/pages/reference/certified.adoc, docs/v0.17/modules/en/pages/tutorials/first-cluster.adoc, docs/v0.17/modules/en/pages/user/caapf.adoc, docs/v0.17/modules/en/pages/user/clusterclass.adoc, docs/v0.17/modules/en/pages/user/clusters.adoc
=> Review and update documentation

docs/next/modules/en/nav.adoc, docs/next/modules/en/pages/tutorials/first-cluster.adoc, docs/v0.17/modules/en/nav.adoc, docs/v0.17/modules/en/pages/tutorials/first-cluster.adoc
Just bumped into `sandbox` mentions while going through the docs
=> Remove `sandbox` mentions and rename chapter to `Features`

docs/next/modules/en/pages/user/clusters.adoc
This PR is fixing Docker RKE2 example
=> Fix issue with generatig Docker RKE2 example

docs/next/modules/en/pages/user/clusterclass.adoc
Just a small url fix pointing to the updated location
=> Fix ClusterClasses example url

docs/next/modules/en/pages/tutorials/first-cluster.adoc, docs/next/modules/en/pages/tutorials/quickstart.adoc
Issue: https://github.com/rancher/turtles-docs/issues/228
=> Add section about how to use quickstart script

docs/next/modules/en/pages/user/clusters.adoc
Fix typu in CLUSTER_CLASS_NAME variable
=> Fix typu in CLUSTER_CLASS_NAME variable

docs/next/modules/en/pages/tutorials/quickstart.adoc
Bump prerequisites versions w.r.t to PR https://github.com/rancher/turtles/pull/1102
=> Bump prerequisites versions

docs/next/modules/en/pages/user/clusters.adoc, package-lock.json
This PR depends on: https://github.com/rancher/turtles/pull/1149
=> Fix namaspace for Azure AKS example

docs/next/modules/en/pages/user/clusterclass.adoc, docs/next/modules/en/pages/user/clusters.adoc
This PR adds the AKS Class example.
Documentation for https://github.com/rancher/turtles/pull/1160
=> Add AKS ClusterClass example

docs/next/modules/en/pages/user/clusterclass.adoc
Documentation to make use of `HelmApp`.
Documentation for: https://github.com/rancher/turtles/pull/1203
=> Use CAAPF and HelmApps for Azure Class example

docs/next/modules/en/pages/user/clusterclass.adoc
Small typo fix.
Documentation update for https://github.com/rancher/turtles/pull/1280
=> Fix typo and broken link

docs/next/modules/en/pages/tutorials/first-cluster.adoc, docs/next/modules/en/pages/user/clusterclass.adoc, docs/next/modules/en/pages/user/clusters.adoc
Fix envsubst command, incorporating changes from https://github.com/rancher/turtles-docs/pull/204/files in new doc structure.
=> Fix envsubst command for first cluster tutorial

docs/next/modules/en/pages/user/clusterclass.adoc
Small fix as this is rendered incorrectly.
=> Fix rendering

docs/next/modules/en/pages/user/clusterclass.adoc, docs/next/modules/en/pages/user/clusters.adoc
Documentation update for https://github.com/rancher/turtles/pull/1280
=> Add vSphere ClusterClass example to documentation

docs/next/modules/en/pages/user/clusterclass.adoc
Fixing small typo in rendering
=> Fix rendering typo

docs/next/modules/en/pages/reference/features.adoc
`agent-tls-mode` has been promoted to beta status.
Part of https://github.com/rancher/turtles/issues/1318
=> :seedling:  Promote agent-tls-mode feature to beta

.gitignore, Makefile, docs/next/modules/en/pages/user/clusterclass.adoc, docs/v0.18/modules/en/pages/user/clusterclass.adoc, docs/v0.19/modules/en/pages/user/clusterclass.adoc
Documentation for https://github.com/rancher/turtles/pull/1319
=> Add vSphere RKE2 Class documentation

docs/next/modules/en/pages/user/clusterclass.adoc
Documentation for: https://github.com/rancher/turtles/pull/1341
Also adding the `kubeadm` provider installation to both vSphere and AWS setups for completeness.
=> Add vSphere Kubeadm documentation

docs/next/modules/en/pages/index.adoc
This PR adds the new demo video created to give users a quick overview of what's possible with Turtles (basic scenario), and updated to use the latest features of Turtles.
Fixes https://github.com/rancher/highlander/issues/131
=> add new demo video using cluster class and fleet

docs/next/modules/en/pages/user/clusterclass.adoc, docs/v0.19/modules/en/pages/user/clusterclass.adoc
Documentation for https://github.com/rancher/turtles/pull/1380
=> Actualize AWS ClusterClass documentation

docs/next/modules/en/pages/user/clusterclass.adoc
Documentation for https://github.com/rancher/turtles/pull/1406
=> CAPV+RKE2 and registration SL Micro against SCC

.github/workflows/publish-version.yaml, tools/setexampleversion/main.go
This PR adds a simple step for our release workflow that sets versions to all examples.
Fixes https://github.com/rancher/turtles-docs/issues/312
=> Set examples versions on release

docs/next/modules/en/nav.adoc, docs/next/modules/en/pages/tutorials/first-cluster.adoc, docs/next/modules/en/pages/user/delete-cluster.adoc
=> Documents Rancher cluster deletion & re-import

docs/next/modules/en/pages/reference/capiprovider.adoc, docs/v0.21/modules/en/pages/reference/capiprovider.adoc
Just minor fix, somehow this worked locally but not when deployed.
=> Fix broken ProviderSpec documentation link

docs/next/modules/en/pages/operator/chart.adoc, docs/next/modules/en/pages/overview/features.adoc
Fixes https://github.com/rancher/turtles-docs/issues/282
=> Remove etcd snapshot restore docs

docs/next/modules/en/pages/reference/capiprovider.adoc
Documentation for https://github.com/rancher/turtles/pull/1601
=> Document CAPIProvider EnableAutomaticUpdate feature

docs/next/modules/en/nav.adoc, docs/next/modules/en/pages/user/cluster-resource-mapping.adoc
=> Cluster Resource Relationships in Turtles
