rancher/turtles-docs

CONTRIBUTING.md
Makefile
hack/generate-doctoc.sh

Fixes: #4 
The plan is, to have a generic CONTRIBUTING guide for all rancher turtles projects (as of now: `rancher-turtles`, `rancher-turtles-docs`, `rancher-turtles-ui` repos) in this repo and refer to it from other repos (`rancher-turtles`, `rancher-turtles-ui`), which means there are some advanced searching queries I had to use in the guide to refer to things like issues in all 3 repos.

:book: Add contributing guide

---

docs/getting-started/create-first-cluster/using_kubectl.md

Add a quickstart guide using kubectl, it's similar to the fleet one https://github.com/rancher-sandbox/rancher-turtles-docs/pull/19 with differences in steps to committing the import label.
Fixes: https://github.com/rancher-sandbox/rancher-turtles-docs/issues/6

Add a quickstart guide using kubectl

---

docs/CONTRIBUTING.md
docs/getting-started/create-first-cluster/using_fleet.md
docs/getting-started/install_capi_operator.md
docs/getting-started/install_turtles_operator.md
docs/tasks/capi-operator/installing_core_provider.md

Some minor aesthetic fixes adding [Docusaurus `notes` and `tips` boxes](https://docusaurus.io/docs/next/markdown-features/admonitions) and  add link to recently merged page `Deployment Scenarios`.

docs: minor updates on internal links and notes

---

docs/getting-started/install_turtles_operator.md

Machine pool feature flag is now enabled for the Core Provider https://github.com/rancher-sandbox/rancher-turtles/pull/152 and this PR updates the list of feature flags in the documentation.

docs: add machine pool to the list of core provider features

---

docs/contributing/development.md
docs/contributing/guidelines.md
docs/contributing/intro.md
hack/generate-doctoc.sh
sidebars.js

This adds a new `contributing` section to the docs and moves the existing contributing guide into this section. The developer setup has also been moved to this new section

docs: added contributing section

---

docs/getting-started/install_turtles_operator.md
docs/getting-started/rancher.md

After validating [Getting Started](https://docs.rancher-turtles.com/docs/category/getting-started), we identified a few improvements:
- If disabling `embedded-cluster-api` during Rancher installation, the cluster must be `clusterctl` initialized to successfully install Rancher. If it is not, it will fail. The problem with this approach is that `clusterctl init` will create namespaces that we're then creating again in the `rancher-turtles` Helm chart. Hence, we decided to document a "standard" installation of Rancher (with `embedded-cluster-api` enabled) and then disabling the feature manually. This fixes the problem with the namespaces.
- Installing `rancher-turtles` after Rancher means that `cert-manager` is already installed in the cluster. If no flag is passed to `rancher-turtles` Helm …

docs: update getting started guide after validation

---

docusaurus.config.js

Currently GitHub link in the book refers to the wrong URL:

Fix rancher-turtles-docs GitHub repo reference

---

docs/getting-started/create-first-cluster/using_fleet.md
docs/getting-started/create-first-cluster/using_kubectl.md
docs/getting-started/rancher.md

This is part of issue https://github.com/rancher-sandbox/rancher-turtles/issues/185.
While we work on a permanent robust solution, we update the docs to add an extra instruction to delete Rancher webhooks that are not removed when disabling the embedded capi functionality in an existing Rancher Manager. This also adds a link to the CAPI documentation on initializing infrastructure providers that I think can be useful for users.

docs: add webhook deletion instructions

---

.github/workflows/version-publish.yaml
README.md
docusaurus.config.js

There are 2 possible approaches to versioning:
- Manual versioning flow. Meaning - you run `yarn docusaurus docs:version v<tag>` and create a PR with updated content. The new version will appear on the page.
- Tag driven flow: someone pushes a new tag to the docs repository. The first step is executed, all changes are committed and pushed to the main page directly. Alternatively, a PR is opened by and automation and then it is getting reviewed (even though there is nothing essential to review, and PR may diverge over time if would not get merged).
This PR implements the second option, which directly pushes into the main branch. 
Fixes: #39

✨Docs versioning, automated

---

docusaurus.config.js

Just fixing a typo in link to `rancher-turtles-docs` GitHub repository before tagging the initial version of the docs.

fix: broken link to github repo

---

docs/intro.md

Changes the demo to be a link to YouTube instead of using an animated gif.

chore: changed demo to be a youtube link

---

docs/getting-started/install_turtles_operator.md
docs/getting-started/rancher.md

With the introduction of the [pre-install Helm hook](https://github.com/rancher-sandbox/rancher-turtles/pull/192) users no longer have to disable embedded CAPI and delete Rancher's remaining webhooks (this is now handled by `helm install`).
This PR adds the following updates:
- Removes pre-installation steps from the Rancher configuration for installing Rancher Turtles.
- Adds an informative section to `Install Rancher Turtles Operator` with the actions applied during the pre-install phase while installing the Rancher Turtles Helm chart.

docs: remove rancher pre-installation requirements

---

docs/getting-started/install_turtles_operator.md
docs/reference-guides/rancher-turtles-chart/values.md
sidebars.js

**What this PR does**
As we add [values](https://github.com/rancher-sandbox/rancher-turtles/blob/main/charts/rancher-turtles/values.yaml) to the Rancher Turtles Helm chart, we need to document the available flags and their usage.
This PR adds a new section under `Reference Guides` focused on the Rancher Turtles Helm chart values and their meaning. It also moves the list of `cluster-api-operator` values that can be passed to this new section and adds a docusaurus [admonitions](https://docusaurus.io/docs/next/markdown-features/admonitions) with a link to the specific reference guide.
**Which issue(s) this PR fixes**:
Fixes #47

docs: add reference guide section for chart values

---

docs/getting-started/install_capi_operator.md
docs/getting-started/install_turtles_operator.md
docs/reference-guides/rancher-turtles-chart/values.md
docs/tasks/capi-operator/add_infrastructure_provider.md
docs/tasks/capi-operator/basic_cluster_api_provider_installation.md
docs/tasks/capi-operator/capiprovider_resource.md
docs/tasks/capi-operator/installing_core_provider.md

This adds documentation for `v0.4.0` CAPIProvider resource, wich is described in [ADR](https://github.com/rancher-sandbox/rancher-turtles/blob/main/docs/adr/0007-rancher-turtles-public-api.md)

:book: Document the CAPIProvider resource for management of CAPI Operator resources

---

docs/getting-started/install_capi_operator.md

When installing CAPI Operator before Rancher Turtles, the installation as a Helm dependency must be disabled to avoid conflicts `cluster-api-operator.enabled=false`.
The section that describes how to install CAPI Operator before Rancher Turtles doesn't link directly to the command required to install Turtles, which may be confusing for users. This change adds a link to the specific Helm install to get Rancher Turtles installed successfully.
Fixes #60

docs: link to installation instructions when capi operator already

---

docs/reference-guides/rancher-turtles-chart/values.md

After merging https://github.com/rancher-sandbox/rancher-turtles/pull/362, a new (optional) feature flag will be available when installing Rancher Turtles. This PR adds this new flag to the chart's list of supported values. 
Fixes #58

docs: add new feature flag for mgmtv3 cluster support

---

docs/getting-started/uninstall_turtles_operator.md
docs/reference-guides/rancher-turtles-chart/values.md
sidebars.js

Related to: https://github.com/rancher-sandbox/rancher-turtles/pull/425

doc: Add Rancher Turtles uninstallation notes

---

docs/tasks/capi-operator/add_infrastructure_provider.md
docs/tasks/capi-operator/basic_cluster_api_provider_installation.md
docs/tasks/capi-operator/capiprovider_resource.md
docs/tasks/capi-operator/installing_core_provider.md

We need to remove stale parts of the documentation related to raw CAPI Operator operations, as the user is expected to use CAPIProvider resource in all cases. This adds a reference to the upstream docs where possible, to keep the users in sync with changes.

Update references to upstream CAPI Operator documentation

---

docs/getting-started/install_turtles_operator.md

After moving repo to rancher/turtles, Helm chart is now available at https://rancher.github.io/turtles/

docs: update references to chart repository

---

docs/contributing/development.md
docs/contributing/guidelines.md
docs/getting-started/install_turtles_operator.md
docs/reference-guides/rancher-turtles-chart/values.md
docs/tasks/capi-operator/capiprovider_resource.md
docusaurus.config.js

Old https://github.com/rancher-sandbox/rancher-turtles-docs repo was moved to new https://github.com/rancher/turtles-docs locations, hence, this PR updates all mentions to old URL in docs and docusaurus configurations

doc: Remove 'sandbox' mentions in docs and configurations

---

versioned_docs/version-0.1/contributing/development.md
versioned_docs/version-0.1/contributing/guidelines.md
versioned_docs/version-0.1/getting-started/install_turtles_operator.md
versioned_docs/version-0.2.0/contributing/development.md
versioned_docs/version-0.2.0/contributing/guidelines.md
versioned_docs/version-0.2.0/getting-started/install_turtles_operator.md
versioned_docs/version-0.2.0/reference-guides/rancher-turtles-chart/values.md
versioned_docs/version-0.3/contributing/development.md
versioned_docs/version-0.3/contributing/guidelines.md
versioned_docs/version-0.3/getting-started/install_turtles_operator.md
versioned_docs/version-0.3/reference-guides/rancher-turtles-chart/values.md
versioned_docs/version-0.4/contributing/development.md
versioned_docs/version-0.4/contributing/guidelines.md
versioned_docs/version-0.4/getting-started/install_turtles_operator.md
versioned_docs/version-0.4/reference-guides/rancher-turtles-chart/values.md
versioned_docs/version-0.4/tasks/capi-operator/capiprovider_resource.md
versioned_docs/version-0.5/contributing/development.md
versioned_docs/version-0.5/contributing/guidelines.md
versioned_docs/version-0.5/getting-started/install_turtles_operator.md
versioned_docs/version-0.5/reference-guides/rancher-turtles-chart/values.md
versioned_docs/version-0.5/tasks/capi-operator/capiprovider_resource.md

All doc references in previous versions are now pointing to correct helm chart repo and repository location.
Fixes: https://github.com/rancher/turtles-docs/issues/72

Replace all references to old repo and old chart location

---

docs/getting-started/install-rancher-turtles/using_rancher_dashboard.md
docs/getting-started/uninstall_turtles.md

Turtles extension has to be removed with `foreground` policy to ensure cleanup of CAPI Operator provisioned resources. This has to be reflected in the docs.

Always specify foreground deletion on uninstall

---

.gitignore
docs/tasks/early_adopter_upgrade.md
sidebars.js

This change adds instructions for the early adopters who want to upgrade to the GA version of Turtles.
Fixes: #78

docs: add instructions for early adopters

---

docs/getting-started/install-rancher-turtles/using_helm.md
docs/tasks/early_adopter_upgrade.md
versioned_docs/version-0.6/getting-started/install-rancher-turtles/using_helm.md

Update Rancher Turtles version number with new release

Change Turtles version number

---

docs/contributing/development.md
docs/contributing/install_capi_operator.md
docs/getting-started/install-rancher-turtles/using_helm.md
sidebars.js
versioned_docs/version-0.6/contributing/development.md
versioned_docs/version-0.6/contributing/install_capi_operator.md
versioned_docs/version-0.6/getting-started/install-rancher-turtles/using_helm.md
versioned_sidebars/version-0.6-sidebars.json

Fixes: https://github.com/rancher/turtles/issues/450
Related PR: https://github.com/rancher/turtles/pull/471
Updates main branch and same changes applied to v0.6 version of docs.

Move CAPI operator installation notes to Contributing section

---

docs/getting-started/install-rancher-turtles/using_rancher_dashboard.md

QA reported that Turtles chart will fail to install if selecting installing into Rancher System Project via Rancher Dashboard https://github.com/rancher/turtles/issues/439. After investigation and discussion with the team, we decided that we do not support this for the time being and we add a note to the installation guide in the documentation stating that the default (not into a project) configuration should be used instead.
Fixes #84

docs: add note on installing app into a project

---

versioned_docs/version-0.6/getting-started/install-rancher-turtles/using_rancher_dashboard.md

Following up on #87, this updates the current `v0.6` of the docs with the new caution note on installing Turtles into a Rancher Project via the UI.
I've never done a docs version update myself, but I assume we'll have to create a new `v0.6` release for it to be updated.

docs: add note on installing into a project (v0.6)

---

docs/getting-started/install-rancher-turtles/using_helm.md
docs/getting-started/install-rancher-turtles/using_rancher_dashboard.md

Users reported that the dependency on `cert-manager` was not visible enough. This PR adds a reminder to check the prerequisites in the installation guide.

docs: add caution admonition with prerequisites

---

docs/reference-guides/providers.md

There's an ongoing effort to get a first version of the CAAPF docs ready for the next release in which the Add-on provider will be optionally enabled in Turtles https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet/pull/51.
This PR adds the provider to the table of providers in experimental state and a link to the markdown docs (this is still broken because at the time of opening this PR the CAAPF one is not yet merged).

docs: add caapf to list of experimental providers

---

docs/reference-guides/providers.md

This PR simply adds CAPD to the list of supported providers with a caution note that it is intended only for development purposes (as specified in the official CAPI docs). As most of our examples for getting started with Turtles use CAPD in some way, it may be relevant to list it in the table together with the other production-ready providers.
**Notes**: this change is not urgent and can be added in the next minor release.

docs: add capd to list of supported providers

---

docs/contributing/install_capi_operator.md
docs/getting-started/intro.md
docs/tasks/capi-operator/add_infrastructure_provider.md
docs/tasks/capi-operator/basic_cluster_api_provider_installation.md

The existing example in Turtles' CAPI Operator docs for installing a `CAPIProvider` refers to upstream's CAPI Operator [book](https://cluster-api-operator.sigs.k8s.io/03_topics/03_basic-cluster-api-provider-installation/02_installing-capz#installing-azure-infrastructure-provider) and Azure Provider. As CAPZ is not yet an officially supported provider in Turtles, we should use a supported provider in the example instead. This changes it from CAPZ to CAPA.

docs: use capa as capi operator example

---

docusaurus.config.js

The current editUrl leads to a 404 when using the "Edit this page" link on a page from versioned_docs.

Fix editUrl

---

docs/getting-started/create-first-cluster/using_fleet.md
docs/getting-started/create-first-cluster/using_kubectl.md

A new CAPD+CAPRKE2 template has been added to the example repository referenced in the getting started guide ([here](https://github.com/rancher-sandbox/rancher-turtles-fleet-example/tree/templates)). This RKE2 base template replaces the old kubeadm-based cluster definition, so users follow the docs with Turtles' default bootstrap/control plane provider.

docs: switch getting-started examples to caprke2

---

docs/contributing/install_capi_operator.md
docs/getting-started/air-gapped-environment.md
docs/getting-started/install-rancher-turtles/using_helm.md
docs/getting-started/install-rancher-turtles/using_rancher_dashboard.md

Some users confuse the development and production installation of the CAPI operator, for production use cases it has to be installed as a dependency. This PR moves the docs to a place that is better suited for them.

Move CAPI Operator installation docs 

---

docs/getting-started/intro.md
docs/tasks/maintenance/early_adopter_upgrade.md
docs/tasks/maintenance/import_controller_upgrade.md
sidebars.js

A guide on how to migrate to the new import controller has been added under a new section `Tasks` -> `Maintenance`. This includes how to use the [migration script](https://github.com/rancher/turtles/pull/574) or apply changes manually. Other similar guides have been moved under this section as well.

docs: add migration guide and maintenance tasks section

---

docs/getting-started/intro.md
sidebars.js

Add a warning on `v0.9.0` home page mentioning the import controller migration and recommending existing users to double-check migration mechanisms and implications.

docs: add warning after import controller migration

---

docs/reference-guides/providers/supported.md

Cluster API Provider for RKE2 is now under `rancher` organization in GitHub. This change simply updates the reference URL in the providers list.

docs: update caprke2 url

---

docs/contributing/intro.md
docs/developer-guide/development.md
docs/developer-guide/install_capi_operator.md
docs/developer-guide/intro.md
docs/reference/contributing_guidelines.md
docs/reference/glossary.md
docs/reference/intro.md
sidebars.js
versioned_docs/version-0.9/contributing/install_capi_operator.md

This is the initial version of glossary added to the book and we can add more acronyms and terms as we go. 
It also includes changes that moves around the docs to the new folder or different which they better correspond and belong.
Fixes: #130

Add glossary for Turtles

---

docs/reference-guides/providers/addon-provider-fleet.md
docs/reference-guides/providers/supported.md
sidebars.js

Add a short overview of functionality for the addon provider Fleet and a demo.
Fixes: https://github.com/rancher/turtles/issues/616

Add CAAPF documentation page

---

docs/reference-guides/providers/howto.md

Add tutorial on how to create AWS clusters with RKE2 provider.
Fixes #117

docs: add capa+caprke2 tutorial

---

docs/reference-guides/providers/certified.md
docs/reference-guides/providers/howto.md
sidebars.js

After discussions with the team and product, we agreed that we should substitute the term "supported" from the documentation and reflect that the providers are verified/validated instead.

docs: reword providers section

---

docs/reference-guides/test-suite/intro.md
docs/reference-guides/test-suite/usage.md
docs/tasks/provider-certification/intro.md
docs/tasks/provider-certification/process.md
sidebars.js

Adding two new sections on:
- How to reuse E2E suite as a user.
- How to certify a new provider as a user.
Fixes #136 
This also links to a new Turtles' issue template for certification request https://github.com/rancher/turtles/pull/681

docs: add provider certif and e2e reuse sections

---

docs/getting-started/cluster-class/intro.md
docs/getting-started/cluster-class/provision.md
docs/reference-guides/providers/certified.md

This PR introduces a new section on cluster classes.
- Adds a guide on how to deploy class and cluster for each provider (tabbed)
- For now only CAPZ is available (it was also added to Turtles E2E). The goal is to have other tabs for the other certified providers that support cluster topology.
- Uses new examples from [rancher-turtles-fleet-examples](https://github.com/rancher-sandbox/rancher-turtles-fleet-example/tree/templates) repo.
- This also adds a sub-section in the `Certified Providers` table with basic information on ClusterClass support for each of the certified providers.
I think we should probably re-think the other cluster class guide (deploying via Fleet) and align both. I'd probably do this in a separate PR.
Fixes #161

extend docs on clusterclass

---

.github/workflows/version-publish.yaml

After cutting a new release, `version-publish` workflow automatically creates a PR to publish a new version of the documentation but CI checks won't execute unless a label is assigned on the PR. Hopefully adding the `area/documentation` label at PR creation will have the same effect and we don't have to manually apply changes.

add label on new version pr

---

.github/workflows/publish.yml

Git sub-module was referenced, as this action is based from the Prime docs which uses it. Removed the reference.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>

Removed sub-module reference

---

.github/workflows/publish.yml

Swapped the build phase to use the local playbook. This is a main difference from the Product docs as the site is built from the same repo, instead of a remote one.
Signed-off-by: Nuno do Carmo <nuno.carmo@suse.com>

Swap remote for local playbook

---

docs/next/modules/en/pages/getting-started/air-gapped-environment.adoc

We started building downstream images and publishing releases for providers, so updating the docs here accordingly.

Refer to downsteam release manifests/images in airgapped docs

---

docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
docs/next/modules/en/pages/getting-started/install-rancher-turtles/using_rancher_dashboard.adoc
docs/v0.15/modules/en/pages/getting-started/install-rancher-turtles/using_helm.adoc
docs/v0.15/modules/en/pages/getting-started/install-rancher-turtles/using_rancher_dashboard.adoc

I slightly changed the wording to clarify the Turtles chart is taking care of Rancher settings, **and** this is the recommended way of handling it (since otherwise it will fail).
I also think this is no longer "important", since it's fully automated by the chart, but still something to be "cautious" about, since it impacts existing Rancher instances.

Clarify recommended way of disabling Rancher features

---

docs/next/modules/en/nav.adoc

Add missing `index` file for newly added automatic release notes publishing. Generating the documentation failed because there was a reference to a non-existent file.

fix: add empty changelogs index file

---

docs/next/modules/en/pages/developer-guide/install_capi_operator.adoc

When installing CAPI operator in stand-alone mode (i.e. not through the Turtles chart) there are some extra resource manifests that need to be applied.
Note that the only other notable difference when installing Turtles with CAPI operator vs when installing Turtles without CAPI operator is that in the latter case, the CAPI operator deployment is missing a [readonly mount for clusterctl-config](https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/values.yaml#L51-L53). Not sure if we need to include this in the instructions as well, please advice.
Closes: #111

docs: Add instructions on installing CAPRKE2 when CAPI operator is disabled in Turtles chart

---

updatecli-compose.yaml

Since moving to Antora, this repository [contains sub-modules](https://github.com/rancher/turtles-docs/blob/main/.gitmodules) which is causing errors when updatecli tries to clone it for the release notes automation. The policy used to control these bumps has been updated to disable sub-modules and avoid this error and this PR simply changes the version of the policy used to point to the latest iteration.

chore: bump updatecli policy for release notes

---

docs/next/modules/en/pages/getting-started/create-first-cluster/using_fleet.adoc
docs/next/modules/en/pages/tasks/capi-operator/capiprovider_resource.adoc

* Allow user to set custom namespace to deploy CAPI cluster to.
* `envsubst` command replaces everything with `$` in the file. This causes `$server` and `$address` to be replaced with empty strings in the resulting `cluster1.yaml` file. Using SHELL-FORMAT ensures `envsubst` replaces only the env vars it's being asked to replace.

🐛 Allow setting custom namespace and fix envsubst command

---

.github/workflows/publish.yml

Should fix the build workflow: https://github.com/rancher/turtles-docs/actions/runs/13332210893
Note that deploy-pages@v4 is required by upload-pages-artifact@v3

Bump actions/upload-pages-artifact and actions/deploy-pages

---

docs/next/modules/en/pages/developer-guide/install_capi_operator.adoc
docs/next/modules/en/pages/getting-started/create-first-cluster/using_fleet.adoc
docs/next/modules/en/pages/getting-started/create-first-cluster/using_kubectl.adoc
docs/next/modules/en/pages/reference-guides/providers/howto.adoc
docs/next/modules/en/pages/tasks/capi-operator/capiprovider_resource.adoc

It is bad practice to use default namespace, due to:
- lack of isolation
- security risks
- resources management
- scalability issues

Do not use default namespace

---

docs/next/modules/en/pages/operator/airgapped.adoc
docs/next/modules/en/pages/operator/manual.adoc
docs/next/modules/en/pages/tutorials/rancher.adoc
docs/next/modules/en/pages/user/clusterclass.adoc
docs/v0.10/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.11/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.12/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.13/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.14/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.15/modules/en/pages/getting-started/air-gapped-environment.adoc
docs/v0.16/modules/en/pages/getting-started/air-gapped-environment.adoc

Hello team! Updating some broken links I found in the `next` version while I was doing some prep to port over the restructure to the product docs. Also noting one link in the `airgapped.adoc/air-gapped-environment.adoc` pages needed to be updated across versions. Please let me know if there are any questions, thank you!

Update Broken Links

---

docs/next/modules/en/pages/tutorials/quickstart.adoc
docs/v0.17/modules/en/pages/tutorials/quickstart.adoc

Updating the components version for v0.17/next as it is still currently displaying v0.16 items. Reference: https://github.com/rancher/turtles/releases/tag/v0.17.0

Updating Components Version - v0.17/next

---

.github/workflows/updatecli.yaml

During release we realized that `updatecli` workflows has been failing for some time now and, after narrowing it down, it looks like it started when dependabot bumped the action's version. For now, let's try to revert this bump and keep the previous version as it looks like the current one is behaving differently when no changed files are detected (which is the case where we see failures). Other projects that use this tool, like Fleet, are also still on the version we're reverting to.
Please, refer to the issue for more context on this and links to the specific action executions where this was first spotted. 
Fixes #235

Updatecli revert releasepost version bump

---

docs/next/modules/en/nav.adoc
docs/next/modules/en/pages/user/clusterclass.adoc
docs/next/modules/en/pages/user/fleet.adoc

This PR adds a new page dedicated to ClusterClasses.
Note that the existing ClusterClass page was actually describing Fleet usage, so I moved all of that to a dedicated Fleet page. That will require rework later on, not part of this PR.
The idea of the new ClusterClasses page, is to follow the model of the "Provisioning a Cluster" documentation, but using ClusterClasses. This new page should ultimately deprecate the "Provisioning a Cluster", when ClusterClasses for all providers are published. 
For this reason the page is meant to be self-contained, also providing instructions and guidance to setup the needed providers, configure identities, and any other step needed to consume the referenced ClusterClass correctly.
Note this is currently blocked by …

Add Azure ClusterClass documentation

---

docs/next/modules/en/pages/tutorials/first-cluster.adoc

Latest [changes](https://github.com/rancher/turtles-docs/commit/2d82680c044bc69649604dd464d7c1b8a9ef77f1) broke the tutorials page only in the `next` version of docs (v0.17 is fine):
and this PR should fix it. Verified it locally:

Fix rendering issue with tab usage

---

docs/next/modules/en/pages/reference/glossary.adoc

Fixes: https://github.com/rancher/turtles-docs/issues/118

📖  Adds general overview of CAPRKE2

---

docs/next/modules/en/pages/user/clusters.adoc

Fixing examples from documentation with adding `kubectl create namespace` command

Add create namespace command for cluster examples

---

docs/next/modules/en/pages/user/clusters.adoc
docs/v0.17/modules/en/pages/user/clusters.adoc

After re-structuring the templates folder in CAPRKE2, there is a broken link that points to the former path.
Fixes #255

fix: broken link after re-structuring caprke2 templates

---

docs/next/modules/en/pages/user/clusterclass.adoc

This makes it consistent with the Cluster definition just below, and does not make assumptions on the namespace used by the user.

Omit default namespace

---

docs/next/modules/en/pages/reference/certified.adoc

The certified providers' table still marks Azure as `AKS clusters only`.

docs: self-managed azure clusters are now supported

---

.github/workflows/updatecli.yaml
updatecli-compose.yaml

The latest version of the `releasepost` GH Action requires minor changes on exit codes in the policy. This change should fix recent failures in the workflow, which runs daily.

Bump `releasepost` policy to align with latest action version

---

docs/next/modules/en/pages/index.adoc
docs/next/modules/en/pages/user/clusters.adoc
docs/v0.18/modules/en/pages/index.adoc
docs/v0.18/modules/en/pages/user/clusters.adoc

Updating the Overview page troubleshooting link and updating the Clusters page that had a missing attribute setting. Additionally escaped the variables on the Clusters page as they were producing a [warning missing attribute error](https://docs.asciidoctor.org/asciidoc/latest/attributes/unresolved-references/#missing:~:text=asciidoctor%3A%20WARNING%3A%20skipping%20reference%20to%20missing%20attribute%3A%20XYZ). I've updated these items in the [v0.18 docs port PR](https://github.com/rancher/turtles-product-docs/pull/39) as well.

[v0.18/Next] Updating Overview and Clusters Page

---

docs/next/modules/en/pages/user/clusterclass.adoc

The `rke2CNI` variable has no default so it has to be set to `none` explicitly for this example.
Calico is installed via HelmApp instead.
If the user would change this variable, multliple CNIs would be installed. 
Also removed the sentence regarding variables to substitute in the load balancer ConfigMap, as there is none and this can be very confusing.

Remove misleading comment, prevent installing many CNIs

---

docs/next/modules/en/pages/user/clusterclass.adoc

We've now created a AWS/Kubeadm ClusterClass examples in Turtles and added it to the test suite. Let's have it covered in the docs, too.

docs: add capa+cabpk class example

---

Makefile
docs/next/modules/en/pages/security/slsa.adoc
docs/next/modules/en/pages/user/clusters.adoc
docs/v0.10/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.10/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.10/modules/en/pages/security/slsa.adoc
docs/v0.11/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.11/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.11/modules/en/pages/security/slsa.adoc
docs/v0.12/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.12/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.12/modules/en/pages/security/slsa.adoc
docs/v0.13/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.13/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.13/modules/en/pages/security/slsa.adoc
docs/v0.14/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.14/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.14/modules/en/pages/security/slsa.adoc
docs/v0.15/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.15/modules/en/pages/reference-guides/rancher-turtles-chart/values.adoc
docs/v0.15/modules/en/pages/security/slsa.adoc
docs/v0.16/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.16/modules/en/pages/security/slsa.adoc
docs/v0.17/modules/en/pages/security/slsa.adoc
docs/v0.17/modules/en/pages/user/clusters.adoc
docs/v0.18/modules/en/pages/security/slsa.adoc
docs/v0.18/modules/en/pages/user/clusters.adoc
docs/v0.19/modules/en/pages/security/slsa.adoc
docs/v0.19/modules/en/pages/user/clusters.adoc
tools/verifybrokenlinks/main.go

This PR adds a simple script to verify that all URLs are valid and fixes all currently broken urls

Add workflow to check for broken urls

---

.gitignore
docs/next/modules/en/pages/user/clusterclass.adoc
docs/next/modules/en/pages/user/clusters.adoc
docs/v0.19/modules/en/pages/user/clusters.adoc

Add docs for creating an RKE2 cluster using EC2 instances, all steps were verified manually, and docs were deployed locally to ensure they render correctly.
Fixes https://github.com/rancher/turtles/issues/1196

Add RKE2+EC2 docs

---

.github/workflows/publish.yml

We can decrease the number of runs to once a day instead of hourly, since it uses personal GH handle as actor to run the workflow and that counts as a contribution in contributions graph

Run Rancher Turtles documentation GH pages publication once a day

---

.github/workflows/pre-release.yaml
.github/workflows/publish-version.yaml
README.adoc
docs/next/modules/en/pages/user/clusters.adoc
docs/v0.13/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.14/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.15/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.16/modules/en/pages/reference-guides/providers/howto.adoc
docs/v0.17/modules/en/pages/operator/certificationsuite.adoc
docs/v0.17/modules/en/pages/user/clusters.adoc
docs/v0.18/modules/en/pages/user/clusterclass.adoc
docs/v0.18/modules/en/pages/user/clusters.adoc
docs/v0.19/modules/en/pages/user/clusterclass.adoc
docs/v0.19/modules/en/pages/user/clusters.adoc
docs/v0.20/modules/en/pages/operator/certificationsuite.adoc
docs/v0.20/modules/en/pages/user/clusterclass.adoc
docs/v0.20/modules/en/pages/user/clusters.adoc
replace-rules.json
tools/setexampleversion/main.go
tools/verifybrokenlinks/main.go

This PR extends the release workflow to bump the Turtles version everywhere on each release. It also adds a new workflow that can update dependency versions based on input: 
The new workflow can run as a pre-release so we can bump dependencies before releasing the new Turtles version. I will add it to the release documentation.
I also fixed all broken/unversioned URLs.
Fixes https://github.com/rancher/turtles-docs/issues/144

Bump Turtles version everywhere on new release 

---

docs/next/modules/en/pages/user/clusterclass.adoc

Documentation for: https://github.com/rancher/turtles/pull/1464
Note that I also took the occasion to align the Azure documentation.
Cluster identities are now used in vSphere, Azure, and AWS examples, making this experience more consistent.

Use AWSClusterStaticIdentity in examples

---

docs/next/modules/en/pages/user/clusterclass.adoc
docs/v0.18/modules/en/pages/user/clusterclass.adoc
docs/v0.19/modules/en/pages/user/clusterclass.adoc
docs/v0.20/modules/en/pages/user/clusterclass.adoc

The current link to CAPZ documentation on how to set up permissions for the provider has been removed. The former site is now a specific guide on how to create a CAPI management cluster on AKS. This PR adds a link to the guide on how to use the different identity methods.

fix: broken link to capz docs

---

docs/next/modules/en/pages/user/clusterclass.adoc

Add guide on how to provision a GCP self-managed clusters based on new ClusterClass template for CAPG/Kubeadm.
Fixes #322

add gcp kubeadm clusterclass example

---

docs/next/modules/en/pages/user/clusterclass.adoc

As a follow-up to #327 (thanks @valaparthvi) this updates the nomenclature used when referring to CCM in both GCP and AWS examples to make it more readable.

update ccm naming for aws and gcp

---

docs/next/modules/en/pages/user/clusterclass.adoc

Documentation for https://github.com/rancher/turtles/pull/1526

Actualize Azure/RKE2 ClusterClass doc

---

docs/next/modules/en/pages/user/clusterclass.adoc

Reverts the warning part of https://github.com/rancher/turtles-docs/pull/313, since https://github.com/rancher/turtles/issues/1402 is fixed

Remove warning for Kubeadm controlplane replica

---

docs/next/modules/en/pages/tutorials/quickstart.adoc

As Cluster API Operator is no longer an external dependency we can drop it from the docs. There's also a reference to a CAPI Operator pod which is no longer installed with Turtles, as it is embedded in the main controller.

remove references to capi operator as external dependency

---

.github/workflows/pre-release.yaml

CAPI Operator will be dropped from the table of requirements so there's no need to have it in the list of component versions to update.

remove capi operator from pre-release component version workflow

---

docs/next/modules/en/pages/operator/airgapped.adoc
docs/next/modules/en/pages/user/clusterclass.adoc
docs/v0.21/modules/en/pages/operator/airgapped.adoc
docs/v0.22/modules/en/pages/operator/airgapped.adoc
docs/v0.23/modules/en/pages/operator/airgapped.adoc

Needed for CAPA v2.9.0 version.

Update AWSClusterStaticIdentity to allow all namespaces

---

docs/v0.18/modules/en/pages/tutorials/quickstart.adoc

FYI the correct version is `v1.9.5`, not `v1.9.6`. See config: https://github.com/rancher/turtles/blob/release-0.18/internal/controllers/clusterctl/config.yaml#L14
I did track down [this PR](https://github.com/rancher/turtles/pull/1159/files) that bumped the cluster-api go dependency, probably it's where v1.9.6 came from.

Correct CAPI version used in v0.18

---

docs/next/modules/en/pages/user/clusterclass.adoc

To be merged after https://github.com/rancher/turtles/pull/1712 is merged.
I am not sure about the location of the document, I added it to next, but it is using the tag `v0.23.0` to fetch the ClusterClass which will not work. This feature will be available in `v0.25.0` since [v0.24.0](https://github.com/rancher/turtles/releases/tag/v0.24.0) was released earlier this week.
----------
_Preview Image:_

Add EKS ClusterClass doc
